//! Autonomous orchestrator for ClaudeCode-style transparent sub-agent coordination.
//!
//! Automatically analyzes tasks, generates execution plans via Supervisor,
//! and coordinates parallel sub-agent execution with result aggregation.

use crate::agents::runtime::AgentRuntime;
use crate::agents::types::AgentResult;
use crate::agents::types::AgentStatus;
use crate::orchestration::CollaborationStore;
use crate::orchestration::ConflictResolver;
use crate::orchestration::MergeStrategy;
use crate::orchestration::TaskAnalysis;
use crate::orchestration::collaboration_store::OrchestrationMetrics;
use anyhow::Result;
use chrono::DateTime;
use chrono::Utc;
use serde::Deserialize;
use serde::Serialize;
use serde_json::json;
use serde_json::to_value;
use std::collections::BTreeSet;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;
use tracing::debug;
use tracing::info;
use tracing::warn;

/// Result of orchestrated execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrchestratedResult {
    /// Whether orchestration was actually used
    pub was_orchestrated: bool,

    /// Agents that were used
    pub agents_used: Vec<String>,

    /// Execution summary
    pub execution_summary: String,

    /// Individual agent results
    pub agent_results: Vec<AgentResult>,

    /// Total execution time in seconds
    pub total_execution_time_secs: f64,

    /// Task analysis that triggered orchestration
    pub task_analysis: TaskAnalysis,

    /// Structured orchestration log entries
    pub orchestration_log: Vec<OrchestrationLogEntry>,
}

/// Detailed orchestration event log entry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrchestrationLogEntry {
    /// Timestamp for the event
    pub timestamp: DateTime<Utc>,
    /// Message describing what happened
    pub message: String,
    /// Skill tag that informed the decision
    pub skill: Option<String>,
    /// Agents selected or executed for the event
    pub selected_agents: Vec<String>,
    /// Strategy used
    pub strategy: ExecutionStrategy,
    /// Fallback chain that was attempted
    pub fallback_chain: Vec<String>,
}

/// Execution plan generated by Supervisor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    /// Goal description
    pub goal: String,

    /// Skill tags that informed this plan
    pub skill_tags: Vec<String>,

    /// List of tasks to execute
    pub tasks: Vec<PlannedTask>,

    /// Execution strategy
    pub strategy: ExecutionStrategy,

    /// Default timeout in seconds to apply to tasks if none provided
    pub timeout_secs: Option<u64>,

    /// Default retry limit for tasks
    pub retry_limit: u8,
}

/// A single task in the execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedTask {
    /// Task ID
    pub id: usize,

    /// Task description
    pub description: String,

    /// Agent assigned to this task
    pub agent: String,

    /// Skill tag that selected this task
    pub skill_tag: Option<String>,

    /// Timeout override for the task
    pub timeout_secs: Option<u64>,

    /// Retry limit override for the task
    pub retry_limit: u8,

    /// Agents to try if the primary agent fails
    pub fallback_agents: Vec<String>,

    /// Task status
    pub status: String,
}

/// Execution strategy for orchestrated tasks.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExecutionStrategy {
    /// Execute all tasks in parallel for maximum speed
    Parallel,
    /// Execute tasks sequentially for dependencies
    Sequential,
    /// Hybrid: parallel where possible, sequential where needed
    Hybrid,
}

#[derive(Debug, Clone)]
struct SkillStrategyConfig {
    agent_loadout: Vec<String>,
    strategy: ExecutionStrategy,
    timeout_secs: Option<u64>,
    retry_limit: u8,
}

/// Autonomous orchestrator that coordinates sub-agents transparently.
pub struct AutoOrchestrator {
    /// Agent runtime for executing sub-agents
    runtime: Arc<AgentRuntime>,

    /// Collaboration store for agent communication
    collaboration_store: Arc<CollaborationStore>,

    /// Conflict resolver for file edits
    conflict_resolver: Arc<ConflictResolver>,

    /// Workspace directory
    workspace_dir: std::path::PathBuf,
}

#[derive(Debug)]
struct AgentExecutionOutcome {
    results: Vec<AgentResult>,
    fallback_used: bool,
}

impl AutoOrchestrator {
    /// Create a new auto-orchestrator.
    pub fn new(
        runtime: Arc<AgentRuntime>,
        collaboration_store: Arc<CollaborationStore>,
        workspace_dir: std::path::PathBuf,
    ) -> Self {
        Self::with_merge_strategy(
            runtime,
            collaboration_store,
            workspace_dir,
            MergeStrategy::Sequential,
        )
    }

    /// Create a new auto-orchestrator with a specific merge strategy.
    pub fn with_merge_strategy(
        runtime: Arc<AgentRuntime>,
        collaboration_store: Arc<CollaborationStore>,
        workspace_dir: std::path::PathBuf,
        merge_strategy: MergeStrategy,
    ) -> Self {
        Self {
            runtime,
            collaboration_store,
            conflict_resolver: Arc::new(ConflictResolver::new(merge_strategy)),
            workspace_dir,
        }
    }

    /// Get a reference to the conflict resolver.
    pub fn conflict_resolver(&self) -> Arc<ConflictResolver> {
        self.conflict_resolver.clone()
    }

    fn skill_strategy_table() -> HashMap<String, SkillStrategyConfig> {
        let mut table = HashMap::new();
        table.insert(
            "security".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["sec-audit".to_string(), "code-reviewer".to_string()],
                strategy: ExecutionStrategy::Hybrid,
                timeout_secs: Some(1_200),
                retry_limit: 2,
            },
        );
        table.insert(
            "rewriter".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["code-reviewer".to_string(), "refactorer".to_string()],
                strategy: ExecutionStrategy::Parallel,
                timeout_secs: Some(900),
                retry_limit: 2,
            },
        );
        table.insert(
            "dependency-analysis".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["dependency-audit".to_string(), "code-reviewer".to_string()],
                strategy: ExecutionStrategy::Sequential,
                timeout_secs: Some(900),
                retry_limit: 2,
            },
        );
        table.insert(
            "testing".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["test-gen".to_string(), "code-reviewer".to_string()],
                strategy: ExecutionStrategy::Parallel,
                timeout_secs: Some(600),
                retry_limit: 1,
            },
        );
        table.insert(
            "documentation".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["researcher".to_string(), "code-reviewer".to_string()],
                strategy: ExecutionStrategy::Hybrid,
                timeout_secs: Some(600),
                retry_limit: 1,
            },
        );
        table.insert(
            "research".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["researcher".to_string(), "code-reviewer".to_string()],
                strategy: ExecutionStrategy::Hybrid,
                timeout_secs: Some(900),
                retry_limit: 1,
            },
        );
        table.insert(
            "general".to_string(),
            SkillStrategyConfig {
                agent_loadout: vec!["code-reviewer".to_string()],
                strategy: ExecutionStrategy::Parallel,
                timeout_secs: Some(600),
                retry_limit: 1,
            },
        );
        table
    }

    fn fallback_table() -> HashMap<String, Vec<String>> {
        HashMap::from([
            ("test-gen".to_string(), vec!["code-reviewer".to_string()]),
            ("sec-audit".to_string(), vec!["code-reviewer".to_string()]),
            ("refactorer".to_string(), vec!["code-reviewer".to_string()]),
            (
                "dependency-audit".to_string(),
                vec!["code-reviewer".to_string()],
            ),
            ("researcher".to_string(), vec!["code-reviewer".to_string()]),
        ])
    }

    fn combine_strategy(
        current: ExecutionStrategy,
        candidate: ExecutionStrategy,
    ) -> ExecutionStrategy {
        match (current, candidate) {
            (ExecutionStrategy::Sequential, _) | (_, ExecutionStrategy::Sequential) => {
                ExecutionStrategy::Sequential
            }
            (ExecutionStrategy::Hybrid, _) | (_, ExecutionStrategy::Hybrid) => {
                ExecutionStrategy::Hybrid
            }
            _ => ExecutionStrategy::Parallel,
        }
    }

    fn record_log(
        &self,
        log_entries: &mut Vec<OrchestrationLogEntry>,
        message: impl Into<String>,
        skill: Option<String>,
        agents: Vec<String>,
        strategy: ExecutionStrategy,
        fallback_chain: Vec<String>,
    ) {
        let entry = OrchestrationLogEntry {
            timestamp: Utc::now(),
            message: message.into(),
            skill,
            selected_agents: agents,
            strategy,
            fallback_chain,
        };
        self.push_log_entry(log_entries, entry);
    }

    fn push_log_entry(
        &self,
        log_entries: &mut Vec<OrchestrationLogEntry>,
        entry: OrchestrationLogEntry,
    ) {
        log_entries.push(entry.clone());
        if let Ok(value) = to_value(log_entries) {
            self.collaboration_store
                .set_metadata("orchestration_log".to_string(), value);
        }
    }

    fn build_failure_result(agent_name: &str, error: String) -> AgentResult {
        AgentResult {
            agent_name: agent_name.to_string(),
            status: AgentStatus::Failed,
            artifacts: vec![],
            tokens_used: 0,
            duration_secs: 0.0,
            error: Some(error),
        }
    }

    fn build_inputs(&self, task: &PlannedTask) -> HashMap<String, String> {
        let mut inputs = HashMap::new();
        inputs.insert("goal".to_string(), task.description.clone());
        inputs.insert(
            "workspace".to_string(),
            self.workspace_dir.display().to_string(),
        );
        inputs.insert("task_id".to_string(), task.id.to_string());

        if let Some(skill) = &task.skill_tag {
            inputs.insert("skill".to_string(), skill.clone());
        }

        let completed_summary = self.collaboration_store.get_results_summary();
        if !completed_summary.is_empty() {
            inputs.insert("previous_results".to_string(), completed_summary);
        }

        inputs
    }

    /// Orchestrate task execution based on analysis.
    pub async fn orchestrate(
        &self,
        analysis: TaskAnalysis,
        original_goal: String,
    ) -> Result<OrchestratedResult> {
        let start_time = Instant::now();
        let mut log_entries = Vec::new();

        info!(
            "🚀 Auto-orchestrating task with complexity {:.2}",
            analysis.complexity_score
        );
        info!("   Recommended agents: {:?}", analysis.recommended_agents);
        info!("   Detected skills: {:?}", analysis.skill_tags);

        // 1. Generate execution plan (simplified - direct agent delegation)
        let plan = self.generate_execution_plan(&analysis, &original_goal, &mut log_entries)?;

        if let Ok(value) = to_value(&plan.skill_tags) {
            self.collaboration_store
                .set_metadata("selected_skills".to_string(), value);
        }
        if let Ok(value) = to_value(&plan.strategy) {
            self.collaboration_store
                .set_metadata("execution_strategy".to_string(), value);
        }

        info!("📋 Execution plan created: {} tasks", plan.tasks.len());

        // 2. Execute agents from plan
        let outcome = self
            .execute_agents_from_plan(&plan, &analysis, &mut log_entries)
            .await?;

        let results = outcome.results;
        let fallback_used = outcome.fallback_used;

        // 3. Merge results
        let execution_summary = self.merge_results(&results);

        let elapsed = start_time.elapsed();
        let total_time = elapsed.as_secs_f64();
        let execution_time_ms = elapsed.as_millis() as u64;

        let metrics = OrchestrationMetrics {
            skills: analysis.detected_keywords.clone(),
            strategy: format!("{:?}", plan.strategy),
            fallback_used,
            agent_count: results.len(),
            execution_time_ms,
            agents: results.iter().map(|r| r.agent_name.clone()).collect(),
        };
        self.collaboration_store.record_metrics(metrics);

        Ok(OrchestratedResult {
            was_orchestrated: true,
            agents_used: results.iter().map(|r| r.agent_name.clone()).collect(),
            execution_summary,
            agent_results: results,
            total_execution_time_secs: total_time,
            task_analysis: analysis,
            orchestration_log: log_entries,
        })
    }

    fn build_plan_for_analysis(
        analysis: &TaskAnalysis,
        original_goal: &str,
    ) -> (ExecutionPlan, Vec<OrchestrationLogEntry>) {
        let mut tasks = Vec::new();
        let mut seen_agents = HashSet::new();
        let mut strategy = ExecutionStrategy::Parallel;
        let mut timeout_secs = None;
        let mut retry_limit = 1;
        let strategy_table = Self::skill_strategy_table();
        let fallback_table = Self::fallback_table();
        let mut log_entries = Vec::new();

        for (idx, skill) in analysis.skill_tags.iter().enumerate() {
            if let Some(config) = strategy_table.get(skill) {
                strategy = Self::combine_strategy(strategy, config.strategy);
                timeout_secs = timeout_secs.max(config.timeout_secs);
                retry_limit = retry_limit.max(config.retry_limit);
                let description =
                    analysis.subtasks.get(idx).cloned().unwrap_or_else(|| {
                        format!("Execute {skill} workflow for: {original_goal}")
                    });

                for agent in &config.agent_loadout {
                    if seen_agents.insert(agent.clone()) {
                        let fallback_agents =
                            fallback_table.get(agent).cloned().unwrap_or_default();
                        tasks.push(PlannedTask {
                            id: tasks.len() + 1,
                            description: description.clone(),
                            agent: agent.clone(),
                            skill_tag: Some(skill.clone()),
                            timeout_secs: config.timeout_secs,
                            retry_limit: config.retry_limit,
                            fallback_agents,
                            status: "pending".to_string(),
                        });
                    }
                }

                log_entries.push(OrchestrationLogEntry {
                    timestamp: Utc::now(),
                    message: format!(
                        "Skill '{}' selected agents {:?} with {:?} strategy",
                        skill, config.agent_loadout, config.strategy
                    ),
                    skill: Some(skill.clone()),
                    selected_agents: config.agent_loadout.clone(),
                    strategy: config.strategy,
                    fallback_chain: vec![],
                });
            }
        }

        for agent in &analysis.recommended_agents {
            if seen_agents.insert(agent.clone()) {
                let description = analysis
                    .subtasks
                    .get(tasks.len())
                    .cloned()
                    .unwrap_or_else(|| format!("Execute {agent} for: {original_goal}"));
                let fallback_agents = fallback_table.get(agent).cloned().unwrap_or_default();
                tasks.push(PlannedTask {
                    id: tasks.len() + 1,
                    description,
                    agent: agent.clone(),
                    skill_tag: None,
                    timeout_secs,
                    retry_limit,
                    fallback_agents,
                    status: "pending".to_string(),
                });
            }
        }

        if tasks.is_empty() {
            let agent = "code-reviewer".to_string();
            let fallback_agents = fallback_table.get(&agent).cloned().unwrap_or_default();
            tasks.push(PlannedTask {
                id: 1,
                description: format!("Review and plan: {original_goal}"),
                agent: agent.clone(),
                skill_tag: Some("general".to_string()),
                timeout_secs: Some(600),
                retry_limit,
                fallback_agents,
                status: "pending".to_string(),
            });
            seen_agents.insert(agent);
        }

        let plan = ExecutionPlan {
            goal: original_goal.to_string(),
            skill_tags: analysis.skill_tags.clone(),
            tasks,
            strategy,
            timeout_secs,
            retry_limit,
        };

        log_entries.push(OrchestrationLogEntry {
            timestamp: Utc::now(),
            message: format!(
                "Execution plan ready: {} tasks, strategy {:?}, timeout {:?}, retry limit {}",
                plan.tasks.len(),
                plan.strategy,
                plan.timeout_secs,
                plan.retry_limit
            ),
            skill: None,
            selected_agents: seen_agents.into_iter().collect(),
            strategy: plan.strategy,
            fallback_chain: vec![],
        });

        (plan, log_entries)
    }

    /// Generate execution plan based on task analysis.
    fn generate_execution_plan(
        &self,
        analysis: &TaskAnalysis,
        original_goal: &str,
        log_entries: &mut Vec<OrchestrationLogEntry>,
    ) -> Result<ExecutionPlan> {
        let (plan, mut planned_logs) = Self::build_plan_for_analysis(analysis, original_goal);

        for entry in planned_logs.drain(..) {
            self.push_log_entry(log_entries, entry);
        }

        Ok(plan)
    }

    /// Execute agents from the execution plan.
    async fn execute_agents_from_plan(
        &self,
        plan: &ExecutionPlan,
        _analysis: &TaskAnalysis,
        log_entries: &mut Vec<OrchestrationLogEntry>,
    ) -> Result<AgentExecutionOutcome> {
        let mut results = Vec::new();
        let mut fallback_used = false;
        self.record_log(
            log_entries,
            format!("Using {:?} strategy", plan.strategy),
            None,
            plan.tasks
                .iter()
                .map(|task| task.agent.clone())
                .collect::<Vec<_>>(),
            plan.strategy,
            vec![],
        );

        let fallback_table = Self::fallback_table();
        let timeout = plan.timeout_secs;
        let retry_limit = plan.retry_limit;

        match plan.strategy {
            ExecutionStrategy::Sequential => {
                for task in &plan.tasks {
                    let (mut task_results, task_fallback_used) = self
                        .execute_task_sequence(
                            task,
                            timeout,
                            retry_limit,
                            &fallback_table,
                            log_entries,
                            plan.strategy,
                        )
                        .await;
                    if task_fallback_used {
                        fallback_used = true;
                    }
                    results.append(&mut task_results);
                }
            }
            ExecutionStrategy::Parallel | ExecutionStrategy::Hybrid => {
                let mut agent_configs = Vec::new();
                for task in &plan.tasks {
                    let inputs = self.build_inputs(task);
                    agent_configs.push((
                        task.agent.clone(),
                        task.description.clone(),
                        inputs,
                        None,
                    ));
                }

                info!("⏳ Executing {} agents in parallel...", agent_configs.len());

                let initial_results = match self
                    .runtime
                    .delegate_parallel(agent_configs.clone(), timeout)
                    .await
                {
                    Ok(agent_results) => agent_results,
                    Err(e) => {
                        warn!("⚠️  Parallel execution failed: {}", e);
                        self.record_log(
                            log_entries,
                            format!("Parallel execution failed: {e}; retrying sequentially"),
                            None,
                            plan.tasks.iter().map(|task| task.agent.clone()).collect(),
                            ExecutionStrategy::Sequential,
                            vec![],
                        );
                        Vec::new()
                    }
                };

                for result in &initial_results {
                    self.collaboration_store
                        .store_agent_result(result.agent_name.clone(), result.clone());
                    let status = result.status.clone();
                    results.push(result.clone());
                    if status != AgentStatus::Completed {
                        if let Some(task) = plan
                            .tasks
                            .iter()
                            .find(|task| task.agent == result.agent_name)
                        {
                            let (mut retry_results, retry_fallback_used) = self
                                .execute_task_sequence(
                                    task,
                                    timeout,
                                    retry_limit,
                                    &fallback_table,
                                    log_entries,
                                    plan.strategy,
                                )
                                .await;
                            if retry_fallback_used {
                                fallback_used = true;
                            }
                            results.append(&mut retry_results);
                        }
                    }
                }

                if initial_results.is_empty() {
                    for task in &plan.tasks {
                        let (mut task_results, task_fallback_used) = self
                            .execute_task_sequence(
                                task,
                                timeout,
                                retry_limit,
                                &fallback_table,
                                log_entries,
                                ExecutionStrategy::Sequential,
                            )
                            .await;
                        if task_fallback_used {
                            fallback_used = true;
                        }
                        results.append(&mut task_results);
                    }
                }
            }
        }

        if results.is_empty() {
            anyhow::bail!("All agents failed to execute");
        }

        info!(
            "✅ Orchestration completed: {} agents executed",
            results.len()
        );

        Ok(AgentExecutionOutcome {
            results,
            fallback_used,
        })
    }

    async fn execute_task_sequence(
        &self,
        task: &PlannedTask,
        plan_timeout: Option<u64>,
        plan_retry_limit: u8,
        fallback_table: &HashMap<String, Vec<String>>,
        log_entries: &mut Vec<OrchestrationLogEntry>,
        strategy: ExecutionStrategy,
    ) -> (Vec<AgentResult>, bool) {
        let mut collected = Vec::new();
        let mut fallback_used = false;
        let timeout = task.timeout_secs.or(plan_timeout);
        let retry_limit = task.retry_limit.max(plan_retry_limit);
        let mut attempt = 0;
        let mut last_error: Option<String> = None;

        while attempt <= retry_limit {
            attempt += 1;
            let inputs = self.build_inputs(task);
            match self
                .runtime
                .delegate(&task.agent, &task.description, inputs, None, timeout)
                .await
            {
                Ok(result) => {
                    self.collaboration_store
                        .store_agent_result(result.agent_name.clone(), result.clone());
                    let status = result.status.clone();
                    last_error = result.error.clone();
                    collected.push(result.clone());
                    if status == AgentStatus::Completed {
                        if attempt > 1 {
                            self.record_log(
                                log_entries,
                                format!("Retry of {} succeeded", task.agent),
                                task.skill_tag.clone(),
                                vec![task.agent.clone()],
                                strategy,
                                vec![],
                            );
                        }
                        return (collected, fallback_used);
                    }
                }
                Err(err) => {
                    let failure = Self::build_failure_result(&task.agent, err.to_string());
                    last_error = failure.error.clone();
                    self.collaboration_store
                        .store_agent_result(task.agent.clone(), failure.clone());
                    collected.push(failure);
                }
            }

            if attempt > retry_limit {
                break;
            }

            self.record_log(
                log_entries,
                format!(
                    "Retrying {} (attempt {} of {})",
                    task.agent,
                    attempt + 1,
                    retry_limit + 1
                ),
                task.skill_tag.clone(),
                vec![task.agent.clone()],
                strategy,
                vec![],
            );
        }

        let mut attempted_chain = Vec::new();
        let fallback_chain = if !task.fallback_agents.is_empty() {
            task.fallback_agents.clone()
        } else {
            fallback_table.get(&task.agent).cloned().unwrap_or_default()
        };

        if !fallback_chain.is_empty() {
            fallback_used = true;
        }

        for fallback_agent in fallback_chain {
            attempted_chain.push(fallback_agent.clone());
            let inputs = self.build_inputs(task);
            match self
                .runtime
                .delegate(&fallback_agent, &task.description, inputs, None, timeout)
                .await
            {
                Ok(result) => {
                    self.collaboration_store
                        .store_agent_result(result.agent_name.clone(), result.clone());
                    let status = result.status.clone();
                    collected.push(result.clone());
                    self.record_log(
                        log_entries,
                        format!(
                            "Fallback to {} after {} attempts{}",
                            fallback_agent,
                            attempt,
                            last_error
                                .as_ref()
                                .map(|err| format!(" (last error: {err})"))
                                .unwrap_or_default()
                        ),
                        task.skill_tag.clone(),
                        vec![fallback_agent.clone()],
                        strategy,
                        attempted_chain.clone(),
                    );
                    if status == AgentStatus::Completed {
                        break;
                    }
                }
                Err(err) => {
                    let failure = Self::build_failure_result(&fallback_agent, err.to_string());
                    last_error = failure.error.clone();
                    self.collaboration_store
                        .store_agent_result(fallback_agent.clone(), failure.clone());
                    collected.push(failure);
                    self.record_log(
                        log_entries,
                        format!("Fallback agent {} failed: {}", fallback_agent, err),
                        task.skill_tag.clone(),
                        vec![fallback_agent.clone()],
                        strategy,
                        attempted_chain.clone(),
                    );
                }
            }
        }

        if !attempted_chain.is_empty() {
            self.collaboration_store
                .set_metadata("fallback_history".to_string(), json!(attempted_chain));
        }

        (collected, fallback_used)
    }

    /// Merge results from multiple agents into a summary.
    fn merge_results(&self, results: &[AgentResult]) -> String {
        let mut summary = String::from("# Orchestrated Execution Summary\n\n");

        summary.push_str(&format!(
            "Executed {} specialized agents:\n\n",
            results.len()
        ));

        for (idx, result) in results.iter().enumerate() {
            summary.push_str(&format!(
                "## Agent {} / {}: {}\n\n",
                idx + 1,
                results.len(),
                result.agent_name
            ));

            summary.push_str(&format!("**Status**: {:?}\n\n", result.status));
            summary.push_str(&format!(
                "**Execution Time**: {:.2}s\n\n",
                result.duration_secs
            ));

            // Include tokens used
            summary.push_str(&format!("**Tokens Used**: {}\n\n", result.tokens_used));

            // Include error if any
            if let Some(ref error) = result.error {
                summary.push_str("**Error**:\n\n");
                for line in error.lines().take(5) {
                    summary.push_str(&format!("{line}\n"));
                }
                summary.push('\n');
            }

            // Include artifacts if any
            if !result.artifacts.is_empty() {
                summary.push_str("**Artifacts**:\n\n");
                for artifact in &result.artifacts {
                    summary.push_str(&format!("- {artifact}\n"));
                }
                summary.push('\n');
            }

            summary.push_str("---\n\n");
        }

        summary
    }

    /// Select agents dynamically based on task analysis.
    ///
    /// Analyzes task requirements and selects the most appropriate agents.
    /// Uses heuristics based on:
    /// - Required skills (from task analysis)
    /// - Task complexity
    /// - Domain specificity
    pub fn select_agents_for_task(&self, analysis: &TaskAnalysis) -> Vec<String> {
        debug!("Selecting agents for task analysis");
        let mut selected_agents = BTreeSet::new();
        let strategy_table = Self::skill_strategy_table();

        for skill in &analysis.skill_tags {
            if let Some(config) = strategy_table.get(skill) {
                selected_agents.extend(config.agent_loadout.iter().cloned());
            }
        }

        selected_agents.extend(analysis.recommended_agents.iter().cloned());

        // Ensure at least one agent is selected
        if selected_agents.is_empty() {
            debug!("No agents selected, defaulting to code-reviewer");
            selected_agents.insert("code-reviewer".to_string());
        }

        info!(
            "Selected {} agents for task: {:?}",
            selected_agents.len(),
            selected_agents
        );

        selected_agents.into_iter().collect()
    }

    /// Determine execution strategy based on task characteristics.
    ///
    /// Analyzes task to decide whether parallel, sequential, or hybrid execution is best.
    pub fn determine_execution_strategy(
        &self,
        task: &PlannedTask,
        _analysis: Option<&TaskAnalysis>,
    ) -> ExecutionStrategy {
        debug!(
            "Determining execution strategy for task: {}",
            task.description
        );

        if let Some(skill) = &task.skill_tag {
            if let Some(config) = Self::skill_strategy_table().get(skill) {
                return config.strategy;
            }
        }

        // Check for keywords indicating sequential dependencies
        let description_lower = task.description.to_lowercase();
        let has_dependencies = description_lower.contains("after")
            || description_lower.contains("then")
            || description_lower.contains("depends on")
            || description_lower.contains("based on");

        if has_dependencies {
            debug!("Task has dependencies, using Sequential strategy");
            return ExecutionStrategy::Sequential;
        }

        // Check for file editing conflicts
        let has_file_edits = description_lower.contains("edit")
            || description_lower.contains("modify")
            || description_lower.contains("change");

        if has_file_edits {
            debug!("Task involves file edits, using Hybrid strategy");
            return ExecutionStrategy::Hybrid;
        }

        // Default to parallel for independent tasks
        debug!("Task appears independent, using Parallel strategy");
        ExecutionStrategy::Parallel
    }

    /// Aggregate results from multiple agents with conflict resolution.
    ///
    /// Combines results while resolving any conflicts in file edits.
    pub fn aggregate_results(&self, results: Vec<AgentResult>) -> Result<OrchestratedResult> {
        debug!("Aggregating {} agent results", results.len());

        let start_time = Instant::now();
        let agents_used: Vec<String> = results.iter().map(|r| r.agent_name.clone()).collect();

        // Merge results using the conflict resolver
        let execution_summary = self.merge_results(&results);

        // Check for conflicts in file edits
        let mut _has_conflicts = false;
        for result in &results {
            if !matches!(result.status, AgentStatus::Completed) {
                _has_conflicts = true;
                let error_msg = result
                    .error
                    .as_ref()
                    .map(ToString::to_string)
                    .unwrap_or_else(|| "Unknown error".to_string());
                warn!("Agent {} failed: {}", result.agent_name, error_msg);
            }
        }

        let task_analysis = TaskAnalysis {
            complexity_score: 0.5,
            detected_keywords: vec![],
            recommended_agents: agents_used.clone(),
            recommended_skill_tags: vec![],
            subtasks: vec![],
            original_input: String::new(),
            skill_tags: vec![],
        };

        Ok(OrchestratedResult {
            was_orchestrated: true,
            agents_used,
            execution_summary,
            agent_results: results,
            total_execution_time_secs: start_time.elapsed().as_secs_f64(),
            task_analysis,
            orchestration_log: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::orchestration::TaskAnalyzer;
    use pretty_assertions::assert_eq;

    #[test]
    fn test_build_plan_uses_skill_strategy_and_loadout() {
        let analyzer = TaskAnalyzer::new(0.5);
        let analysis = analyzer.analyze("Perform security audit and refactor the module");

        let (plan, logs) =
            AutoOrchestrator::build_plan_for_analysis(&analysis, &analysis.original_input);

        assert_eq!(plan.strategy, ExecutionStrategy::Hybrid);
        assert_eq!(plan.timeout_secs, Some(1_200));
        assert_eq!(plan.retry_limit, 2);
        assert!(
            plan.tasks
                .iter()
                .any(|task| task.agent == "sec-audit"
                    && task.skill_tag.as_deref() == Some("security"))
        );
        assert!(plan.tasks.iter().any(|task| task.agent == "refactorer"));
        assert!(plan.tasks.iter().any(|task| task.agent == "code-reviewer"));
        assert!(
            logs.iter()
                .any(|entry| entry.message.contains("selected agents"))
        );
    }

    #[test]
    fn test_dependency_analysis_plan_sets_fallbacks() {
        let analysis = TaskAnalysis {
            complexity_score: 0.8,
            detected_keywords: vec!["dependency".to_string()],
            skill_tags: vec!["dependency-analysis".to_string()],
            recommended_agents: vec![],
            recommended_skill_tags: vec![],
            subtasks: vec!["audit dependencies".to_string()],
            original_input: "audit dependencies".to_string(),
        };

        let (plan, logs) =
            AutoOrchestrator::build_plan_for_analysis(&analysis, &analysis.original_input);

        assert_eq!(plan.strategy, ExecutionStrategy::Sequential);
        let dependency_task = plan
            .tasks
            .iter()
            .find(|task| task.agent == "dependency-audit")
            .expect("task for dependency-audit");
        assert_eq!(
            dependency_task.fallback_agents,
            vec!["code-reviewer".to_string()]
        );
        assert_eq!(dependency_task.retry_limit, 2);
        assert!(
            logs.iter()
                .any(|entry| entry.strategy == ExecutionStrategy::Sequential)
        );
    }
}
