// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/v2/CommandExecOutputStream.ts
 * Stream label for `command/exec/outputDelta` notifications.
 */
export type CommandExecOutputStream = "stdout" | "stderr";
========
 * [UNSTABLE] Source that produced a terminal approval auto-review decision.
 */
export type AutoReviewDecisionSource = "agent";
>>>>>>>> upstream/main:codex-rs/app-server-protocol/schema/typescript/v2/AutoReviewDecisionSource.ts
