// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { Git4DMode } from "./Git4DMode";
import type { Git4DSessionStatus } from "./Git4DSessionStatus";

export type Git4DSessionSummary = { sessionId: string, repositoryPath: AbsolutePathBuf, requestedMode: Git4DMode, effectiveMode: Git4DMode, status: Git4DSessionStatus, platform: string | null, deviceName: string | null, fallbackReason: string | null, uptimeMs: bigint, idleMs: bigint, };
