// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/Git4DMode.ts
export type Git4DMode = "desktop" | "vr" | "ar";
========
export type HookMigration = { name: string, };
>>>>>>>> upstream/main:codex-rs/app-server-protocol/schema/typescript/v2/HookMigration.ts
