// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginInstallParams = { marketplacePath: AbsolutePathBuf, pluginName: string, 
/**
 * When true, apply the remote plugin change before the local install flow.
 */
forceRemoteSync?: boolean, };
export type PluginInstallParams = { marketplacePath: AbsolutePathBuf, pluginName: string, };
// STASHED: export type PluginInstallParams = { marketplacePath: AbsolutePathBuf, pluginName: string, 
// STASHED: /**
// STASHED:  * When true, apply the remote plugin change before the local install flow.
// STASHED:  */
// STASHED: forceRemoteSync?: boolean, };

