/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveredManagedLayers {
    #[serde(rename = "baseline")]
    pub baseline: Vec<models::DeliveredTomlFragment>,
    #[serde(rename = "system_overlay")]
    pub system_overlay: Vec<models::DeliveredTomlFragment>,
}

impl DeliveredManagedLayers {
    pub fn new(
        baseline: Vec<models::DeliveredTomlFragment>,
        system_overlay: Vec<models::DeliveredTomlFragment>,
    ) -> DeliveredManagedLayers {
        DeliveredManagedLayers {
            baseline,
            system_overlay,
        }
    }
}
