//! OpenXR bindings generated by bindgen
//!
//! Based on: https://github.com/KhronosGroup/OpenXR-SDK

#[cfg(feature = "openxr")]
include!(concat!(env!("OUT_DIR"), "/openxr_bindings.rs"));

#[cfg(not(feature = "openxr"))]
// Stub types when OpenXR feature is disabled
pub mod stub {
    pub type XrInstance = *mut std::ffi::c_void;
    pub type XrSession = *mut std::ffi::c_void;
    pub type XrSystemId = u64;
    pub type XrResult = i32;
    
    pub const XR_SUCCESS: XrResult = 0;
    pub const XR_ERROR_RUNTIME_FAILURE: XrResult = 1;
    pub const XR_ERROR_INSTANCE_LOST: XrResult = 2;
}











