[package]
edition = "2024"
name = "mcp-types"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ts-rs = { version = "10.0", features = ["serde-json-impl", "no-serde-warnings"] }
schemars = "0.8"
