[package]
edition = "2024"
name = "mcp-types"
version = "2.3.0"

[lints]
rust.unused_qualifications = "warn"
rust.unreachable = "warn"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ts-rs = { version = "10.0", features = ["serde-json-impl", "no-serde-warnings"] }
schemars = "0.8"
