// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Git4DSessionEvent } from "./Git4DSessionEvent";

export type Git4DSessionEventNotification = { sessionId: string, sequence: bigint, event: Git4DSessionEvent, };
