// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Git4DSessionStatus } from "./Git4DSessionStatus";

export type Git4DSessionEvent = { "type": "commits_loaded", commit_count: number, } | { "type": "branches_updated", branch_count: number, branch_names: Array<string>, } | { "type": "camera_updated", position: [number, number, number], target: [number, number, number], } | { "type": "render_complete", pixel_bytes: number, } | { "type": "interaction_processed", interaction: string, } | { "type": "error", message: string, } | { "type": "session_status_changed", status: Git4DSessionStatus, };
