// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/RealtimeConversationVersion.ts
export type RealtimeConversationVersion = "v1" | "v2";
========
export type RealtimeOutputModality = "text" | "audio";
>>>>>>>> upstream/main:codex-rs/app-server-protocol/schema/typescript/RealtimeOutputModality.ts
