// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
<<<<<<<< HEAD:codex-rs/app-server-protocol/schema/typescript/v2/AutoReviewDecisionSource.ts
 * [UNSTABLE] Source that produced a terminal approval auto-review decision.
 */
export type AutoReviewDecisionSource = "agent";
========
 * Display item emitted by the interruptible `clock.sleep` tool.
 */
export type SleepItem = { id: string, durationMs: number, };
>>>>>>>> upstream/main:codex-rs/app-server-protocol/schema/typescript/SleepItem.ts
